language: shell
before_install:
- sudo apt-get install texlive-latex-extra
script:
- ./build.sh
- cd built_package/pdfjam*
- unzip tests.zip
- tests/run.sh
- shellcheck --exclude=SC1004 bin/pdfjam
# blocklist
branches:
  except:
  - devel

  