language: shell
before_install:
- sudo apt-get install texlive-latex-extra
script:
- ./build.sh
- built_package/pdfjam*/tests/run.sh
- shellcheck --exclude=SC1004 built_package/pdfjam*/bin/pdfjam
# blocklist
branches:
  except:
  - devel
  - built_for_release
  